
import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/styles/globals.css";
import { CartProvider } from '@/context/cartcontext';
import { cn } from "@/lib/utils";

const geistSans = localFont({
  src: "/fonts/GeistVF.woff", 
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "/fonts/GeistMonoVF.woff", 
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadados para SEO e informações gerais
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Layout principal da aplicação
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased"
        )}
      >
        {/* Envolvendo o conteúdo com o provedor de contexto do carrinho */}
        <CartProvider>
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
